version: "3.8"

services:
  service:
    build: .
    container_name: "api-gateway"
    environment:
      REST_PORT: "8000"
      JWT_SECRET_KEY: "jwt_secret_key"
    ports:
      - "8000:8000"
    networks:
      - fullstack

volumes:
  database_mysql:

networks:
  fullstack:
    driver: bridge